### ISSUE TITLE
Notify the project is open source in the chrome store

### ISSUE THREAD

**Issue by touilleMan** [jarrodek/feed-reader#1]
Hi, and thank you for your app !

I was looking for a simple open source rss reader and it ends up it was not as easy as I thought:
 - Most open source rss reader are desktop application (sometime even working as server !)
 - The only browser app rss reader I found was https://github.com/ancestorak/brief, but it was for firefox

So all in all your project seems really filling a need.
But to end up on this github page and make sure the project is opensource, I had to google your name... lucky your not "John Smith" ^^

So I think you should make mention of it "opensourceness" directly on the chrome store and add a link to the Github page (and vice-versa).

Thanks again,

Emmanuel

**Comment by jarrodek** [comment]
Added, changed :)

**Comment by jarrodek** [comment]
Thanks for pointing this out!

**Comment by touilleMan** [comment]
:+1:
